server:
  port: 8090
spring:
  profiles:
    include: password
  cloud:
    gateway:
      default-filters:
        - AddResponseHeader=source, api
      routes:
        - id: api_route
          uri: http://localhost:8123
          predicates:
            - Path=/api/**

logging:
  level:
    org:
      springframework:
        cloud:
          gateway: trace
dubbo:
  application:
    name: api-gateway
  protocol:
    name: dubbo
    port: -1
  registry:
    id: nacos-registry
    address: nacos://${nacos.url}